/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/login/access-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login Access Token */
        post: operations["login-login_access_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/login/test-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Token */
        post: operations["login-test_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/password-recovery/{email}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recover Password */
        post: operations["login-recover_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reset-password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["login-reset_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/password-recovery-html-content/{email}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recover Password Html Content */
        post: operations["login-recover_password_html_content"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Users */
        get: operations["users-read_users"];
        put?: never;
        /** Create User */
        post: operations["users-create_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read User Me */
        get: operations["users-read_user_me"];
        put?: never;
        post?: never;
        /** Delete User Me */
        delete: operations["users-delete_user_me"];
        options?: never;
        head?: never;
        /** Update User Me */
        patch: operations["users-update_user_me"];
        trace?: never;
    };
    "/api/v1/users/me/become-provider": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Become Provider
         * @description Self-service ``customer → provider`` upgrade (HIGH-4).
         *
         *     Returns the same payload as ``GET /users/me`` so a client can
         *     diff the ``user_type`` field locally without an extra round trip.
         *     The provider record this user creates afterwards still goes
         *     through the admin verification step (UC-10).
         */
        post: operations["users-become_provider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Password Me */
        patch: operations["users-update_password_me"];
        trace?: never;
    };
    "/api/v1/users/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register User */
        post: operations["users-register_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read User By Id */
        get: operations["users-read_user_by_id"];
        put?: never;
        post?: never;
        /** Delete User */
        delete: operations["users-delete_user"];
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["users-update_user"];
        trace?: never;
    };
    "/api/v1/utils/test-email/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Email
         * @description Test emails.
         */
        post: operations["utils-test_email"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/utils/health-check/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["utils-health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Discover Providers */
        get: operations["providers-discover_providers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Provider */
        post: operations["providers-create_provider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{provider_id}/access-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Provider Access Code
         * @description Staff-only read of the rotating access code (CRIT-1).
         *
         *     The public ``ProviderPublic`` payload deliberately omits the code so
         *     third parties can't fetch it via ``GET /providers/{id}``. Owners and
         *     staff retrieve it through this dedicated endpoint instead.
         */
        get: operations["providers-read_provider_access_code"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/by-slug/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Provider By Slug */
        get: operations["providers-read_provider_by_slug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{provider_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Provider */
        get: operations["providers-read_provider"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Provider */
        patch: operations["providers-update_provider"];
        trace?: never;
    };
    "/api/v1/providers/{provider_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Provider Members */
        get: operations["providers-list_provider_members"];
        put?: never;
        /** Add Provider Member */
        post: operations["providers-add_provider_member"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{provider_id}/members/{member_user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Provider Member */
        delete: operations["providers-remove_provider_member"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/providers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List My Providers
         * @description List every provider the logged-in user has a membership in.
         *
         *     Returns the same fields as ``GET /providers/{id}`` plus
         *     ``membership_role`` (``owner`` / ``staff``) so the dashboard can
         *     badge the row without an extra round trip. Sorted by newest first.
         */
        get: operations["providers-list_my_providers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/providers/{provider_id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin Verify Provider
         * @description Admin (UC-10) flips a pending provider to ``verified`` so it
         *     appears in public discovery.
         */
        post: operations["admin-admin_verify_provider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/providers/{provider_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin Reject Provider
         * @description Admin (UC-10) marks a provider as ``rejected`` — it stays out of
         *     public discovery and the owner sees the status on their dashboard.
         */
        post: operations["admin-admin_reject_provider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{provider_id}/services/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Service Items */
        get: operations["service-items-list_service_items"];
        put?: never;
        /** Create Service Item */
        post: operations["service-items-create_service_item"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{provider_id}/services/{service_item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Service Item */
        patch: operations["service-items-update_service_item"];
        trace?: never;
    };
    "/api/v1/service-items/me/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Active Tickets */
        get: operations["queue-my_active_tickets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/service-items/{service_item_id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join Queue */
        post: operations["queue-join_queue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/service-items/{service_item_id}/walk-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Walk In */
        post: operations["queue-register_walk_in"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/service-items/{service_item_id}/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tickets For Service */
        get: operations["queue-list_tickets_for_service"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/service-items/{service_item_id}/call-next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Call Next */
        post: operations["queue-call_next"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/service-items/{service_item_id}/tickets/{ticket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cancel My Ticket
         * @description Customer leaves their own queue spot (CRIT-4).
         *
         *     Owner-only — staff use the PATCH endpoint to mark no-show or
         *     complete. No strike is recorded for a voluntary cancel.
         */
        delete: operations["queue-cancel_my_ticket"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/service-items/{service_item_id}/tickets/{ticket_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Ticket Status */
        patch: operations["queue-update_ticket_status"];
        trace?: never;
    };
    "/api/v1/tickets/{ticket_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Review */
        post: operations["reviews-create_review"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{provider_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Provider Reviews */
        get: operations["reviews-list_provider_reviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{provider_id}/rating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Provider Rating */
        get: operations["reviews-get_provider_rating"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/strikes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Strikes */
        get: operations["strikes-get_my_strikes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/unblock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin Unblock User */
        post: operations["admin-admin_unblock_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{provider_id}/broadcasts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Broadcasts
         * @description List broadcasts for a provider.
         *
         *     * **Staff / owner / admin** receive every broadcast for the provider
         *       (operational messages targeted at any service line).
         *     * **Customers** with an active (waiting/serving) ticket on the
         *       provider receive only the broadcasts that fan out to *their*
         *       lines — both provider-wide messages and service-scoped ones for
         *       the lines they're on. This is the REST counterpart to the
         *       ``broadcast_v1`` events on the ticket WebSocket so a brief drop
         *       doesn't lose them messages (CRIT-5).
         *     * **Anyone else** gets 403.
         */
        get: operations["broadcasts-list_broadcasts"];
        put?: never;
        /** Post Broadcast */
        post: operations["broadcasts-post_broadcast"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Notifications */
        get: operations["notifications-list_my_notifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update My Notification Prefs */
        patch: operations["notifications-update_my_notification_prefs"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_login-login_access_token */
        "Body_login-login_access_token": {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /**
         * BroadcastCreate
         * @description Body of ``POST /providers/{provider_id}/broadcasts``.
         *
         *     ``service_item_id``: when omitted, the broadcast targets *every* active
         *     service line of the provider; otherwise just the specified one.
         *
         *     ``idempotency_key``: optional client-supplied de-dupe key. The unique
         *     index on the column means a retried request with the same key returns
         *     the originally created record without re-publishing the realtime event.
         */
        BroadcastCreate: {
            /** Body */
            body: string;
            /**
             * Severity
             * @default info
             */
            severity: string;
            /** Service Item Id */
            service_item_id?: string | null;
            /** Idempotency Key */
            idempotency_key?: string | null;
        };
        /** BroadcastPublic */
        BroadcastPublic: {
            /** Body */
            body: string;
            /**
             * Severity
             * @default info
             */
            severity: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Provider Id
             * Format: uuid
             */
            provider_id: string;
            /** Service Item Id */
            service_item_id?: string | null;
            /**
             * Author User Id
             * Format: uuid
             */
            author_user_id: string;
            /** Created At */
            created_at?: string | null;
        };
        /** BroadcastsPublic */
        BroadcastsPublic: {
            /** Data */
            data: components["schemas"]["BroadcastPublic"][];
            /** Count */
            count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MembershipCreate */
        MembershipCreate: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** @default staff */
            role: components["schemas"]["MembershipRole"];
        };
        /** MembershipPublic */
        MembershipPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Provider Id
             * Format: uuid
             */
            provider_id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Role */
            role: string;
        };
        /**
         * MembershipRole
         * @enum {string}
         */
        MembershipRole: "owner" | "staff";
        /** Message */
        Message: {
            /** Message */
            message: string;
        };
        /**
         * MyProviderPublic
         * @description Row shape for ``GET /users/me/providers``.
         *
         *     Extends ``ProviderPublic`` with the caller's role on that provider so
         *     the dashboard can badge "Owner" vs "Staff" without a second query.
         */
        MyProviderPublic: {
            /** Slug */
            slug: string;
            /** Biz Name */
            biz_name: string;
            /**
             * Verification Status
             * @default pending
             */
            verification_status: string;
            /**
             * Is Open
             * @default true
             */
            is_open: boolean;
            /**
             * Is Paused
             * @default false
             */
            is_paused: boolean;
            /** Join Radius M */
            join_radius_m?: number | null;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /**
             * Is Private
             * @default false
             */
            is_private: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Created At */
            created_at?: string | null;
            /**
             * Ratings Count
             * @default 0
             */
            ratings_count: number;
            /** Rating Avg */
            rating_avg?: number | null;
            /** Membership Role */
            membership_role: string;
        };
        /** MyProvidersPublic */
        MyProvidersPublic: {
            /** Data */
            data: components["schemas"]["MyProviderPublic"][];
            /** Count */
            count: number;
        };
        /** NewPassword */
        NewPassword: {
            /** Token */
            token: string;
            /** New Password */
            new_password: string;
        };
        /**
         * NotificationPrefsUpdate
         * @description Body of ``PATCH /users/me/notifications``.
         */
        NotificationPrefsUpdate: {
            /**
             * Notification Prefs
             * @description Ordered list of channel keys (e.g. ["websocket","email"]); the first deliverable channel wins per dispatch. Channels not recognised by the server are rejected with 400.
             */
            notification_prefs: string[];
        };
        /** NotificationPublic */
        NotificationPublic: {
            /** Kind */
            kind: string;
            /** Body */
            body: string;
            /** Channel */
            channel: string;
            /** Status */
            status: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ticket Id */
            ticket_id?: string | null;
            /** Position */
            position?: number | null;
            /** Created At */
            created_at?: string | null;
        };
        /** NotificationsPublic */
        NotificationsPublic: {
            /** Data */
            data: components["schemas"]["NotificationPublic"][];
            /** Count */
            count: number;
        };
        /** ProviderCreate */
        ProviderCreate: {
            /** Slug */
            slug: string;
            /** Biz Name */
            biz_name: string;
            /**
             * Verification Status
             * @default pending
             */
            verification_status: string;
            /**
             * Is Open
             * @default true
             */
            is_open: boolean;
            /**
             * Is Paused
             * @default false
             */
            is_paused: boolean;
            /** Join Radius M */
            join_radius_m?: number | null;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /**
             * Is Private
             * @default false
             */
            is_private: boolean;
            /** Owner User Id */
            owner_user_id?: string | null;
            /** Access Code */
            access_code?: string | null;
        };
        /** ProviderDiscoveriesPublic */
        ProviderDiscoveriesPublic: {
            /** Data */
            data: components["schemas"]["ProviderDiscoveryPublic"][];
            /** Count */
            count: number;
        };
        /** ProviderDiscoveryPublic */
        ProviderDiscoveryPublic: {
            /** Slug */
            slug: string;
            /** Biz Name */
            biz_name: string;
            /**
             * Verification Status
             * @default pending
             */
            verification_status: string;
            /**
             * Is Open
             * @default true
             */
            is_open: boolean;
            /**
             * Is Paused
             * @default false
             */
            is_paused: boolean;
            /** Join Radius M */
            join_radius_m?: number | null;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /**
             * Is Private
             * @default false
             */
            is_private: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Created At */
            created_at?: string | null;
            /**
             * Ratings Count
             * @default 0
             */
            ratings_count: number;
            /** Rating Avg */
            rating_avg?: number | null;
            /** Distance M */
            distance_m?: number | null;
            /**
             * Active Tickets
             * @default 0
             */
            active_tickets: number;
            /**
             * Serving Tickets
             * @default 0
             */
            serving_tickets: number;
            /** Estimated Wait Minutes */
            estimated_wait_minutes?: number | null;
            /** Load Factor */
            load_factor?: string | null;
        };
        /** ProviderPublic */
        ProviderPublic: {
            /** Slug */
            slug: string;
            /** Biz Name */
            biz_name: string;
            /**
             * Verification Status
             * @default pending
             */
            verification_status: string;
            /**
             * Is Open
             * @default true
             */
            is_open: boolean;
            /**
             * Is Paused
             * @default false
             */
            is_paused: boolean;
            /** Join Radius M */
            join_radius_m?: number | null;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /**
             * Is Private
             * @default false
             */
            is_private: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Created At */
            created_at?: string | null;
            /**
             * Ratings Count
             * @default 0
             */
            ratings_count: number;
            /** Rating Avg */
            rating_avg?: number | null;
        };
        /** ProviderRatingSummary */
        ProviderRatingSummary: {
            /**
             * Provider Id
             * Format: uuid
             */
            provider_id: string;
            /**
             * Ratings Count
             * @default 0
             */
            ratings_count: number;
            /** Rating Avg */
            rating_avg?: number | null;
            /** Estimate Accuracy Rate */
            estimate_accuracy_rate?: number | null;
        };
        /**
         * ProviderStaffPublic
         * @description Staff/owner view: includes the rotating access code so staff can
         *     share it. Returned by ``GET /providers/{id}/access-code``.
         */
        ProviderStaffPublic: {
            /** Slug */
            slug: string;
            /** Biz Name */
            biz_name: string;
            /**
             * Verification Status
             * @default pending
             */
            verification_status: string;
            /**
             * Is Open
             * @default true
             */
            is_open: boolean;
            /**
             * Is Paused
             * @default false
             */
            is_paused: boolean;
            /** Join Radius M */
            join_radius_m?: number | null;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /**
             * Is Private
             * @default false
             */
            is_private: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Created At */
            created_at?: string | null;
            /**
             * Ratings Count
             * @default 0
             */
            ratings_count: number;
            /** Rating Avg */
            rating_avg?: number | null;
            /** Access Code */
            access_code?: string | null;
        };
        /** ProviderUpdate */
        ProviderUpdate: {
            /** Biz Name */
            biz_name?: string | null;
            /** Is Open */
            is_open?: boolean | null;
            /** Is Paused */
            is_paused?: boolean | null;
            /** Join Radius M */
            join_radius_m?: number | null;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /** Is Private */
            is_private?: boolean | null;
            /** Access Code */
            access_code?: string | null;
        };
        /** QueueEntriesPublic */
        QueueEntriesPublic: {
            /** Data */
            data: components["schemas"]["QueueEntryPublic"][];
            /** Count */
            count: number;
        };
        /** QueueEntryPublic */
        QueueEntryPublic: {
            /** Ticket Number */
            ticket_number: number;
            /**
             * Status
             * @default waiting
             */
            status: string;
            /** Source */
            source: string;
            /** Guest Name */
            guest_name?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Service Item Id
             * Format: uuid
             */
            service_item_id: string;
            /** User Id */
            user_id?: string | null;
            /** Joined At */
            joined_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
        };
        /** QueueJoin */
        QueueJoin: {
            /** Access Code */
            access_code?: string | null;
        };
        /** ReviewCreate */
        ReviewCreate: {
            /** Rating */
            rating: number;
            /** Was Estimate Accurate */
            was_estimate_accurate: boolean;
            /** Comment */
            comment?: string | null;
        };
        /** ReviewPublic */
        ReviewPublic: {
            /** Rating */
            rating: number;
            /** Was Estimate Accurate */
            was_estimate_accurate: boolean;
            /** Comment */
            comment?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Ticket Id
             * Format: uuid
             */
            ticket_id: string;
            /**
             * Provider Id
             * Format: uuid
             */
            provider_id: string;
            /**
             * Service Item Id
             * Format: uuid
             */
            service_item_id: string;
            /** Created At */
            created_at?: string | null;
        };
        /** ReviewsPublic */
        ReviewsPublic: {
            /** Data */
            data: components["schemas"]["ReviewPublic"][];
            /** Count */
            count: number;
        };
        /** ServiceItemCreate */
        ServiceItemCreate: {
            /** Name */
            name: string;
            /** Avg Duration Minutes */
            avg_duration_minutes: number;
            /** Price */
            price: number | string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** ServiceItemPublic */
        ServiceItemPublic: {
            /** Name */
            name: string;
            /** Avg Duration Minutes */
            avg_duration_minutes: number;
            /** Price */
            price: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Provider Id
             * Format: uuid
             */
            provider_id: string;
        };
        /** ServiceItemUpdate */
        ServiceItemUpdate: {
            /** Name */
            name?: string | null;
            /** Avg Duration Minutes */
            avg_duration_minutes?: number | null;
            /** Price */
            price?: number | string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /**
         * TicketStatus
         * @enum {string}
         */
        TicketStatus: "waiting" | "serving" | "completed" | "no_show" | "cancelled";
        /** TicketStatusUpdate */
        TicketStatusUpdate: {
            status: components["schemas"]["TicketStatus"];
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UpdatePassword */
        UpdatePassword: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Is Superuser
             * @default false
             */
            is_superuser: boolean;
            /** Full Name */
            full_name?: string | null;
            /** Phone Number */
            phone_number?: string | null;
            /**
             * User Type
             * @default customer
             */
            user_type: string;
            /** Password */
            password: string;
        };
        /** UserPublic */
        UserPublic: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Is Superuser
             * @default false
             */
            is_superuser: boolean;
            /** Full Name */
            full_name?: string | null;
            /** Phone Number */
            phone_number?: string | null;
            /**
             * User Type
             * @default customer
             */
            user_type: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Created At */
            created_at?: string | null;
            /** Joins Blocked Until */
            joins_blocked_until?: string | null;
            /** Notification Prefs */
            notification_prefs?: string[] | null;
        };
        /** UserRegister */
        UserRegister: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name?: string | null;
            /**
             * User Type
             * @default customer
             * @enum {string}
             */
            user_type: "customer" | "provider";
        };
        /** UserStrikePublic */
        UserStrikePublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Ticket Id
             * Format: uuid
             */
            ticket_id: string;
            /**
             * Provider Id
             * Format: uuid
             */
            provider_id: string;
            /** Kind */
            kind: string;
            /** Created At */
            created_at?: string | null;
        };
        /** UserStrikesPublic */
        UserStrikesPublic: {
            /** Data */
            data: components["schemas"]["UserStrikePublic"][];
            /** Count */
            count: number;
            /** Joins Blocked Until */
            joins_blocked_until?: string | null;
            /** Window Days */
            window_days: number;
            /** Limit */
            limit: number;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Email */
            email?: string | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Is Superuser
             * @default false
             */
            is_superuser: boolean;
            /** Full Name */
            full_name?: string | null;
            /** Phone Number */
            phone_number?: string | null;
            /**
             * User Type
             * @default customer
             */
            user_type: string;
            /** Password */
            password?: string | null;
        };
        /**
         * UserUpdateMe
         * @description Self-edit payload for ``PATCH /users/me``.
         *
         *     Deliberately *does not* include ``user_type`` — role upgrades go
         *     through the dedicated ``POST /users/me/become-provider`` endpoint
         *     so identity changes don't ride along with profile edits (HIGH-4).
         */
        UserUpdateMe: {
            /** Full Name */
            full_name?: string | null;
            /** Email */
            email?: string | null;
            /** Phone Number */
            phone_number?: string | null;
        };
        /** UsersPublic */
        UsersPublic: {
            /** Data */
            data: components["schemas"]["UserPublic"][];
            /** Count */
            count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WalkInCreate */
        WalkInCreate: {
            /** Guest Name */
            guest_name?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "login-login_access_token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login-login_access_token"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "login-test_token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
        };
    };
    "login-recover_password": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                email: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "login-reset_password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewPassword"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "login-recover_password_html_content": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                email: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "users-read_users": {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsersPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "users-create_user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "users-read_user_me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
        };
    };
    "users-delete_user_me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    "users-update_user_me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateMe"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "users-become_provider": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
        };
    };
    "users-update_password_me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePassword"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "users-register_user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegister"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "users-read_user_by_id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "users-delete_user": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "users-update_user": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "utils-test_email": {
        parameters: {
            query: {
                email_to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "utils-health_check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": boolean;
                };
            };
        };
    };
    "providers-discover_providers": {
        parameters: {
            query: {
                latitude: number;
                longitude: number;
                radius_m?: number | null;
                query?: string | null;
                include_private?: boolean;
                only_open?: boolean;
                include_paused?: boolean;
                include_unverified?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderDiscoveriesPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "providers-create_provider": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "providers-read_provider_access_code": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderStaffPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "providers-read_provider_by_slug": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "providers-read_provider": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "providers-update_provider": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "providers-list_provider_members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "providers-add_provider_member": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MembershipCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "providers-remove_provider_member": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
                member_user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "providers-list_my_providers": {
        parameters: {
            query?: {
                /** @description Optional membership role filter. Use 'owner' to list only businesses the user owns; omit to list every provider where they have any membership. */
                role?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyProvidersPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "admin-admin_verify_provider": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "admin-admin_reject_provider": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "service-items-list_service_items": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceItemPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "service-items-create_service_item": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceItemPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "service-items-update_service_item": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
                service_item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceItemUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceItemPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "queue-my_active_tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueEntriesPublic"];
                };
            };
        };
    };
    "queue-join_queue": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueueJoin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueEntryPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "queue-register_walk_in": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WalkInCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueEntryPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "queue-list_tickets_for_service": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueEntriesPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "queue-call_next": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueEntryPublic"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "queue-cancel_my_ticket": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_item_id: string;
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueEntryPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "queue-update_ticket_status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_item_id: string;
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueEntryPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "reviews-create_review": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "reviews-list_provider_reviews": {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewsPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "reviews-get_provider_rating": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderRatingSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "strikes-get_my_strikes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserStrikesPublic"];
                };
            };
        };
    };
    "admin-admin_unblock_user": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "broadcasts-list_broadcasts": {
        parameters: {
            query?: {
                /** @description ISO-8601 timestamp; only broadcasts with `created_at >= since` are returned. Use the previous response's most-recent `created_at` to page forward. */
                since?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BroadcastsPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "broadcasts-post_broadcast": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BroadcastCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BroadcastPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "notifications-list_my_notifications": {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationsPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "notifications-update_my_notification_prefs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationPrefsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
